### ISSUE TITLE
KeyError in full training and association testing pipeline

### ISSUE THREAD

**Issue by m4mbo** [PMBio/deeprvat#114]
## Overview
Running into keyError when specifying less (or different) phenotypes for association testing than training. 
## Cause
Error pops up at line 564 in the [update_config](https://github.com/PMBio/deeprvat/blob/main/deeprvat/deeprvat/config.py) function. Caused by calling `seed_config = config["phenotypes"][phenotype]` since phenotypes used only in training are not stored in the 'phenotypes' key.
## Potential solutions
Perhaps adding an option for `--training-only` could be beneficial?

**Comment by meyerkm** [comment]
Thanks for noticing this and reaching out! I've created a PR with a fix, to allow a user to not have to list training phenotypes as part of the association testing phenotypes list. 
Once that PR is accepted into main, this should fix your KeyError!
