### ISSUE TITLE
How do I get "cache" and "plugins" under "ensembl-vep"

### ISSUE THREAD

**Issue by pichuan** [PMBio/deeprvat#115]
Hi,

I'm reading:
https://deeprvat.readthedocs.io/en/latest/annotations.html#configure-the-annotation-pipeline

Which mentioned this structure:

```
|-- repo_dir
|   |-- ensembl-vep
|   |   |-- cache
|   |   |-- plugins
```

I did this earlier:

```
git clone https://github.com/Ensembl/ensembl-vep.git
mkdir repo_dir
mv ensembl-vep repo_dir/
```

So I have:

```
$ ls repo_dir/ensembl-vep/
INSTALL.pl  README.md         cpanfile  examples    haplo    nextflow  travisci   variant_recoder
LICENSE     convert_cache.pl  docker    filter_vep  modules  t         validator  vep
```

But I don't have the "cache" and "plugins" directories.

I did try something like:

```
pichuan@pichuan-gpu:~/repo_dir/ensembl-vep$ perl INSTALL.pl
ERROR: DBI module not found. VEP requires the DBI perl module to function

http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#requirements
```

Before I try to figure out how to run `perl INSTALL.pl`, I want to check whether that's necessary, or if you have some other suggestions on how I should get the "cache" and "plugins" directoresi to be under "ensembl-vep".

Thanks!

**Comment by Marcel-Mueck** [comment]
Hey @pichuan yes, running the install script is the easiest way to get vep configured and the cache downloaded

**Comment by pichuan** [comment]
Thank you @Marcel-Mueck .

I'm encountering some issues downloading one of the cache file. It always crashes at this point:

```
 - downloading https://ftp.ensembl.org/pub/release-112/variation/indexed_vep_cache/bos_taurus_vep_112_ARS-UCD1.3.tar.gz
ERROR: checksum for /home/pichuan/.vep/tmp/bos_taurus_vep_112_ARS-UCD1.3.tar.gz doesn't match checksum in CHECKSUMS file on FTP site
```

Any suggestions? If that cache file is not required, I can also skip it.

Thanks!

**Comment by Marcel-Mueck** [comment]
Hey @pichuan only the cache for _homo sapiens_ is required for this analysis, so you do not need this particular cache file. If the cache does not work at all, you can run the annotation pipeline without cache by setting `vep_online` to false, but I would recommand trying to download the cache for a shorter runtime.

**Comment by pichuan** [comment]
Thanks @Marcel-Mueck . I ended up installing:

```
483 : homo_sapiens_merged_vep_112_GRCh38.tar.gz (29 GB)
485 : homo_sapiens_refseq_vep_112_GRCh38.tar.gz (27 GB)
487 : homo_sapiens_vep_112_GRCh38.tar.gz (27 GB)
```

At first I tried everything including the GRCh37 ones, but I got an error, so I went with just the GRCh38 ones.
Hopefully that's ok.

One more question: **Which Plugins should I install?** There seems to be a long list as well. I'll start with all, but I figure I might need all (and that it might not succeed)

**Comment by pichuan** [comment]
Actually, I went with `all` for Plugins, and it seems fine. Some said the data are not downloaded so I can't install, but I think that's fine too. ( I can't actually use some of them).

I'll proceed with the instructions on https://deeprvat.readthedocs.io/en/latest/annotations.html, and will ask another question again if I have other blockers.
