### ISSUE TITLE
deeprvat installation error

### ISSUE THREAD

**Issue by AppWick-hub** [PMBio/deeprvat#124]
Dear developers of deeprvat,
When I try to clone the github repository using: 

git clone git@github.com:PMBio/deeprvat.git 

I got an error saying: 

ssh: connect to host github.com port 22: connection refused
fatal: could not read from remote repository 

Please make sure you have the correct access rights and the repository exists 

Then I tried: 

git clone https://github.com/PMBio/deeprvat.git 

and it worked.. 

Then when I tried to install deeprvat as follow:

mamba env create -n deeprvat -f deeprvat_env.yaml

getting an Error saying : 

LibMambaUnsatisfiableError: Encountered problems while solving: 
  - package cudatoolkit-11.8.0-h6a678d5_0 is excluded by strict repo priority 
  - package numpy-1.26.0-py312heda63a1_0 requires python_abi 3.12.* *_cp312, but none of the providers can be installed.

Any idea how can I fix this? 

Best,
A

**Comment by endast** [comment]
Hi @AppWick-hub 
if you run `conda config --show channel_priority` does the output say 
`channel_priority: strict`?

If so you could try and set channel_priority to flexible:

`conda config --set channel_priority flexible`

**Comment by AppWick-hub** [comment]
Hey,
After changing channel priority as per your instruction, when I re-run the deeprvat installation command, a pip subprocess error has been occurred. 

Please find the attached screenshot.

![deeprvat installation issue_2](https://github.com/user-attachments/assets/18ac84b2-749e-4fc0-b1bf-d957fecff71a)

**Comment by endast** [comment]
Hi
seak is installed using pip so it does not manage everything as automatically as the stuff installed using mamba.
So you might have to install cargo manually
https://doc.rust-lang.org/cargo/getting-started/installation.html

**Comment by AppWick-hub** [comment]
Hi,

Yes, I used something similar and have run the following:

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

Then have repeated the installation process and deeprvat seemed to be installed. 

But, then I try the following as instructed to check if it has been installed properly:

mkdir deeprvat_associate
cd deeprvat_associate
ln -s [path_to_deeprvat]/example/* .
ln -s [path_to_deeprvat]/pretrained_models
snakemake -j 1 --snakefile [path_to_deeprvat]/pipelines/association_testing_pretrained.snakefile

but getting an error saying: 

"No module named deeprvat"

N.B: I have change the path_to_deeprvat. 

Am I missing anything here?

**Comment by endast** [comment]
Hi
Yes after setting up the environment and activating it you need to install the deeprvat package in the environment:
https://deeprvat.readthedocs.io/en/latest/installation.html

**Comment by AppWick-hub** [comment]
Hi Again,
I did miss to run :

pip install -e .

and it has been installed now. 

However, when I run the following to test:

mkdir deeprvat_associate
cd deeprvat_associate
ln -s [path_to_deeprvat]/example/* .
ln -s [path_to_deeprvat]/pretrained_models
snakemake -j 1 --snakefile [path_to_deeprvat]/pipelines/association_testing_pretrained.snakefile

it does retuning an error saying: 

No such file or directory: deeprvat_input_pretrained_models_config.yaml

**Comment by endast** [comment]
Hi
Did you change `[path_to_deeprvat]` to the actual path of the deeprvat repo?

for example if you cloned the repo to your home folder `/home/appwick/deeprvat`


the commands should look like this

```shell
mkdir deeprvat_associate
cd deeprvat_associate
ln -s /home/appwick/deeprvat/example/* .
ln -s /home/appwick/deeprvat/pretrained_models
snakemake -j 1 --snakefile /home/appwick/deeprvat/pipelines/association_testing_pretrained.snakefile
```

or you could use relative paths 


```shell
mkdir deeprvat_associate
cd deeprvat_associate
ln -s ../deeprvat/example/* .
ln -s ..deeprvat/pretrained_models
snakemake -j 1 --snakefile ..deeprvat/pipelines/association_testing_pretrained.snakefile
```

Depending on where and how you created the example directory.

**Comment by AppWick-hub** [comment]
Hey,
I started again and am getting the following error:

![deeprvat installation issue_3](https://github.com/user-attachments/assets/0d2eae25-1d9f-4d33-8942-33f47569838b)

Below is the whole process I followed:

At the home directory: /home/appwick/ cloned the github repository:

git clone https://github.com/PMBio/deeprvat.git

cd deeprvat/ 

mamba env create -n deeprvat -f deeprvat_env.yaml


conda activate deeprvat 

pip install -e .

mkdir deeprvat_associate

cd deeprvat_associate

ln -s /home/appwick/deeprvat/example/* .

ln -s /home/appwick/deeprvat/pretrained_models

snakemake -j 1 --snakefile /home/appwick/deeprvat/pipelines/association_testing_pretrained.snakefile

**Comment by endast** [comment]
Hi
Ok, i see the problem, we recently consolidated the configs and the docs needs to be updated a bit to reflect this. I will have a look at this and get back to you.

**Comment by endast** [comment]
@AppWick-hub we have updated the docs and some of the config paths now in this PR https://github.com/PMBio/deeprvat/pull/129 could you please try again?

**Comment by AppWick-hub** [comment]
Yes, its working now. Thanks
