### ISSUE TITLE
MMsplice rule doesn't work for some genes?

### ISSUE THREAD

**Issue by Antonio-Nappi** [PMBio/deeprvat#148]
Hi, thanks for this pipeline. I have extracted the main features that I need to build my own pipeline and it works for almost all the genes (16k out of 19k) for some my version of [mmsplice rule](https://github.com/PMBio/deeprvat/blob/113fa722b3e3b6b70c19a50968905522aae34c8d/pipelines/resources/absplice_splicing_pred_DNA.snakefile#L26) is not working since the SpliceOutlierDataloader is empty thus it fails when I call `model.predict_save(dl, output_file)`, do you have any idea?

**Comment by Marcel-Mueck** [comment]
Hey Antonio, 
do you have an example gene where the rule is specifically not working? I could then have a look into it
LG Marcel

**Comment by Antonio-Nappi** [comment]
Hi Marcel, sorry for the late reply but I figured out, the gene was not expressed in a tissue so it was not producing a score.
