### ISSUE TITLE
Instruction pages for preprocessing and annotation cannot be reached

### ISSUE THREAD

**Issue by ChristianDina** [PMBio/deeprvat#4]
Hi, thanks a lot for this tool that I am happy to test on our data. As stated in the "Object", I cannot reach the instruction pages. Not sure it is a problem on my side ...
Best wishes
Christian

**Comment by endast** [comment]
Hi Christian
Here are direct links to the instructions for the preprocessing and annotation:
https://github.com/bfclarke/deeprvat/blob/master/deeprvat/preprocessing/README.md
https://github.com/bfclarke/deeprvat/blob/master/deeprvat/annotations/README.md

Please tell us if you run into any issues.

**Comment by ChristianDina** [comment]
Thanks, yes I have the same problem 

![Image2](https://github.com/PMBio/deeprvat/assets/7311147/2b2e4625-07f3-43d3-91ad-6b758906c9a6)

**Comment by hkmztrk** [comment]
Hi @ChristianDina, thanks a lot for your interest!
The public urls should be accessible from this repo: 
https://github.com/PMBio/deeprvat/tree/main/deeprvat/preprocessing
https://github.com/PMBio/deeprvat/tree/main/deeprvat/annotations

**Comment by endast** [comment]
The links in the main readme is wrong we will update them :)

**Comment by endast** [comment]
https://github.com/PMBio/deeprvat/pull/5 the links are updated now with this PR, so i'm closing this issue.
