### ISSUE TITLE
Inconsistent columns during concat_annotations

### ISSUE THREAD

**Issue by Jonas-B-Frank** [PMBio/deeprvat#63]
Executing the annotation pipeline after the introduction of #54 (using --forceall in the snakemake command to ensure all possibly already existing files are regenerated) I get the following error during the execution of rule `concat_annotations`, line 1955 of `annotations.py`:

`Traceback (most recent call last):
  File "PATH/deeprvat/annotations/annotations.py", line 1947, in concat_annotations
    file.to_parquet(out_file, engine="fastparquet", append=True)
  File "PATH/miniconda3/envs/deeprvat_annotations/lib/python3.9/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "PATH/miniconda3/envs/deeprvat_annotations/lib/python3.9/site-packages/pandas/core/frame.py", line 2976, in to_parquet
    return to_parquet(
  File "PATH/miniconda3/envs/deeprvat_annotations/lib/python3.9/site-packages/pandas/io/parquet.py", line 430, in to_parquet
    impl.write(
  File "PATH/miniconda3/envs/deeprvat_annotations/lib/python3.9/site-packages/pandas/io/parquet.py", line 312, in write
    self.api.write(
  File "PATH/miniconda3/envs/deeprvat_annotations/lib/python3.9/site-packages/fastparquet/writer.py", line 1273, in write
    pf.write_row_groups(data, row_group_offsets, sort_key=None,
  File "PATH/miniconda3/envs/deeprvat_annotations/lib/python3.9/site-packages/fastparquet/api.py", line 543, in write_row_groups
    raise ValueError(
ValueError: Column names of new data are ['AATF_k5', 'AF', 'AGGF1_hg2', 'AGGF1_k5', 'AGO1_parclip', 'AGO2_parclip', 'AGO3_parclip', 'AKAP1_hg2', 'AKAP1_k5', 'AKAP8L_k5', 'AQR_hg2', 'AQR_k5', 'BCLAF1_hg2', 'BIOTYPE', 'BUD13_hg2', 'BUD13_k5', 'CADD_PHRED', 'CADD_RAW', 'CAPRIN1_parclip', 'CDC40_hg2', 'CPSF1_parclip', 'CPSF3_parclip', 'CPSF4_parclip', 'CPSF6_parclip', 'CPSF7_parclip', 'CSTF2T_hg2', 'CSTF2T_k5', 'CSTF2T_parclip', 'CSTF2_hg2', 'CSTF2_parclip', 'Consequence', 'Consequence_3_prime_UTR_variant', 'Consequence_5_prime_UTR_variant', 'Consequence_NMD_transcript_variant', 'Consequence_TFBS_ablation', 'Consequence_TF_binding_site_variant', 'Consequence_coding_sequence_variant', 'Consequence_downstream_gene_variant', 'Consequence_frameshift_variant', 'Consequence_incomplete_terminal_codon_variant', 'Consequence_inframe_deletion', 'Consequence_inframe_insertion', 'Consequence_intergenic_variant', 'Consequence_intron_variant', 'Consequence_mature_miRNA_variant', 'Consequence_missense_variant', 'Consequence_non_coding_transcript_exon_variant', 'Consequence_non_coding_transcript_variant', 'Consequence_protein_altering_variant', 'Consequence_regulatory_region_variant', 'Consequence_splice_acceptor_variant', 'Consequence_splice_donor_5th_base_variant', 'Consequence_splice_donor_region_variant', 'Consequence_splice_donor_variant', 'Consequence_splice_polypyrimidine_tract_variant', 'Consequence_splice_region_variant', 'Consequence_start_lost', 'Consequence_start_retained_variant', 'Consequence_stop_gained', 'Consequence_stop_lost', 'Consequence_stop_retained_variant', 'Consequence_synonymous_variant', 'Consequence_transcript_ablation', 'Consequence_upstream_gene_variant', 'DDX24_k5', 'DDX3X_hg2', 'DDX3X_k5', 'DDX52_k5', 'DDX55_hg2', 'DDX55_k5', 'DDX59_hg2', 'DDX6_k5', 'DGCR8_hg2', 'DGCR8_k5', 'DHX30_k5', 'DICER1_parclip', 'DISTANCE', 'DKC1_hg2', 'DND1_parclip', 'DROSHA_hg2', 'DROSHA_k5', 'EFTUD2_hg2', 'EFTUD2_k5', 'EIF3A_parclip', 'EIF3D_parclip', 'EIF3G_parclip', 'EIF3H_hg2', 'EIF4G2_k5', 'ELAVL1_parclip', 'ELAVL2_parclip', 'ELAVL3_parclip', 'ELAVL4_parclip', 'EWSR1_k5', 'EWSR1_parclip', 'EXOSC5_k5', 'FAM120A_hg2', 'FAM120A_k5', 'FBL_parclip', 'FIP1L1_parclip', 'FKBP4_hg2', 'FMR1_k5', 'FMR1iso1_parclip', 'FMR1iso7_parclip', 'FUBP3_hg2', 'FUS_k5', 'FUS_parclip', 'FXR1_k5', 'FXR1_parclip', 'FXR2_hg2', 'FXR2_k5', 'FXR2_parclip', 'G35_parclip', 'G3BP1_hg2', 'G45_parclip', 'GEMIN5_k5', 'GPKOW_k5', 'GRSF1_hg2', 'GRWD1_hg2', 'GRWD1_k5', 'GTF2F1_hg2', 'GTF2F1_k5', 'Gene', 'HLTF_hg2', 'HNRNPC_hg2', 'HNRNPD_parclip', 'HNRNPK_hg2', 'HNRNPK_k5', 'HNRNPL_hg2', 'HNRNPL_k5', 'HNRNPM_hg2', 'HNRNPM_k5', 'IGF2BP1_hg2', 'IGF2BP1_k5', 'IGF2BP1_parclip', 'IGF2BP2_k5', 'IGF2BP2_parclip', 'IGF2BP3_hg2', 'IGF2BP3_parclip', 'ILF3_hg2', 'ILF3_k5', 'KHDRBS1_k5', 'KHSRP_hg2', 'KHSRP_k5', 'L1RE1_parclip', 'LARP4_hg2', 'LIN28A_parclip', 'LIN28B_hg2', 'LIN28B_k5', 'LIN28B_parclip', 'LSM11_hg2', 'LSM11_k5', 'MATR3_hg2', 'MATR3_k5', 'MBNL1_parclip', 'METAP2_k5', 'MOV10_parclip', 'MTPAP_k5', 'NCBP2_hg2', 'NKRF_hg2', 'NOLC1_hg2', 'NOLC1_k5', 'NONO_k5', 'NOP56_parclip', 'NOP58_parclip', 'NUDT21_parclip', 'ORF1_parclip', 'P53_NONO_parclip', 'PABPC4_k5', 'PABPN1_hg2', 'PAPD5_parclip', 'PCBP1_k5', 'PCBP2_hg2', 'PPIG_hg2', 'PRPF4_hg2', 'PRPF8_hg2', 'PRPF8_k5', 'PTBP1_hg2', 'PTBP1_k5', 'PUM1_k5', 'PUM2_k5', 'PUM2_parclip', 'PolyPhen', 'PrimateAI', 'QKI_hg2', 'QKI_k5', 'QKI_parclip', 'RBFOX2_hg2', 'RBFOX2_k5', 'RBM10_parclip', 'RBM15_hg2', 'RBM15_k5', 'RBM20_parclip', 'RBM22_hg2', 'RBM22_k5', 'RBPMS_parclip', 'RPS3_hg2', 'RPS3_k5', 'RTCB_parclip', 'SAFB2_k5', 'SF3A3_hg2', 'SF3B4_hg2', 'SF3B4_k5', 'SFPQ_hg2', 'SIFT', 'SLTM_hg2', 'SLTM_k5', 'SMNDC1_k5', 'SND1_hg2', 'SND1_k5', 'SRRM4_parclip', 'SRSF1_hg2', 'SRSF1_k5', 'SSB_parclip', 'STRAND', 'SUB1_hg2', 'SUGP2_hg2', 'SpliceAI_delta_score', 'SpliceAI_pred', 'TAF15_parclip', 'TARDBP_k5', 'TARDBP_parclip', 'TIA1_hg2', 'TIA1_k5', 'TIAL1_hg2', 'TRA2A_k5', 'U2AF1_hg2', 'U2AF1_k5', 'U2AF2_hg2', 'U2AF2_k5', 'UCHL5_hg2', 'UCHL5_k5', 'UPF1_hg2', 'UPF1_k5', 'UPF1_parclip', 'XPO5_hg2', 'XPO5_parclip', 'XRN2_hg2', 'XRN2_k5', 'YBX3_hg2', 'YBX3_k5', 'ZC3H11A_hg2', 'ZC3H11A_k5', 'ZC3H7B_parclip', 'ZFP36_parclip', 'ZNF622_k5', 'ZNF800_hg2', 'ZNF800_k5', 'alt', 'chrom', 'id', 'index', 'pos', 'ref']. But column names in existing file are ['AATF_k5', 'AF', 'AGGF1_hg2', 'AGGF1_k5', 'AGO1_parclip', 'AGO2_parclip', 'AGO3_parclip', 'AKAP1_hg2', 'AKAP1_k5', 'AKAP8L_k5', 'AQR_hg2', 'AQR_k5', 'BCLAF1_hg2', 'BIOTYPE', 'BUD13_hg2', 'BUD13_k5', 'CADD_PHRED', 'CADD_RAW', 'CAPRIN1_parclip', 'CDC40_hg2', 'CPSF1_parclip', 'CPSF3_parclip', 'CPSF4_parclip', 'CPSF6_parclip', 'CPSF7_parclip', 'CSTF2T_hg2', 'CSTF2T_k5', 'CSTF2T_parclip', 'CSTF2_hg2', 'CSTF2_parclip', 'Consequence', 'Consequence_3_prime_UTR_variant', 'Consequence_5_prime_UTR_variant', 'Consequence_NMD_transcript_variant', 'Consequence_TFBS_ablation', 'Consequence_TF_binding_site_variant', 'Consequence_coding_sequence_variant', 'Consequence_downstream_gene_variant', 'Consequence_frameshift_variant', 'Consequence_incomplete_terminal_codon_variant', 'Consequence_inframe_deletion', 'Consequence_inframe_insertion', 'Consequence_intergenic_variant', 'Consequence_intron_variant', 'Consequence_mature_miRNA_variant', 'Consequence_missense_variant', 'Consequence_non_coding_transcript_exon_variant', 'Consequence_non_coding_transcript_variant', 'Consequence_protein_altering_variant', 'Consequence_regulatory_region_variant', 'Consequence_splice_acceptor_variant', 'Consequence_splice_donor_5th_base_variant', 'Consequence_splice_donor_region_variant', 'Consequence_splice_donor_variant', 'Consequence_splice_polypyrimidine_tract_variant', 'Consequence_splice_region_variant', 'Consequence_start_lost', 'Consequence_start_retained_variant', 'Consequence_stop_gained', 'Consequence_stop_lost', 'Consequence_stop_retained_variant', 'Consequence_synonymous_variant', 'Consequence_upstream_gene_variant', 'DDX24_k5', 'DDX3X_hg2', 'DDX3X_k5', 'DDX52_k5', 'DDX55_hg2', 'DDX55_k5', 'DDX59_hg2', 'DDX6_k5', 'DGCR8_hg2', 'DGCR8_k5', 'DHX30_k5', 'DICER1_parclip', 'DISTANCE', 'DKC1_hg2', 'DND1_parclip', 'DROSHA_hg2', 'DROSHA_k5', 'EFTUD2_hg2', 'EFTUD2_k5', 'EIF3A_parclip', 'EIF3D_parclip', 'EIF3G_parclip', 'EIF3H_hg2', 'EIF4G2_k5', 'ELAVL1_parclip', 'ELAVL2_parclip', 'ELAVL3_parclip', 'ELAVL4_parclip', 'EWSR1_k5', 'EWSR1_parclip', 'EXOSC5_k5', 'FAM120A_hg2', 'FAM120A_k5', 'FBL_parclip', 'FIP1L1_parclip', 'FKBP4_hg2', 'FMR1_k5', 'FMR1iso1_parclip', 'FMR1iso7_parclip', 'FUBP3_hg2', 'FUS_k5', 'FUS_parclip', 'FXR1_k5', 'FXR1_parclip', 'FXR2_hg2', 'FXR2_k5', 'FXR2_parclip', 'G35_parclip', 'G3BP1_hg2', 'G45_parclip', 'GEMIN5_k5', 'GPKOW_k5', 'GRSF1_hg2', 'GRWD1_hg2', 'GRWD1_k5', 'GTF2F1_hg2', 'GTF2F1_k5', 'Gene', 'HLTF_hg2', 'HNRNPC_hg2', 'HNRNPD_parclip', 'HNRNPK_hg2', 'HNRNPK_k5', 'HNRNPL_hg2', 'HNRNPL_k5', 'HNRNPM_hg2', 'HNRNPM_k5', 'IGF2BP1_hg2', 'IGF2BP1_k5', 'IGF2BP1_parclip', 'IGF2BP2_k5', 'IGF2BP2_parclip', 'IGF2BP3_hg2', 'IGF2BP3_parclip', 'ILF3_hg2', 'ILF3_k5', 'KHDRBS1_k5', 'KHSRP_hg2', 'KHSRP_k5', 'L1RE1_parclip', 'LARP4_hg2', 'LIN28A_parclip', 'LIN28B_hg2', 'LIN28B_k5', 'LIN28B_parclip', 'LSM11_hg2', 'LSM11_k5', 'MATR3_hg2', 'MATR3_k5', 'MBNL1_parclip', 'METAP2_k5', 'MOV10_parclip', 'MTPAP_k5', 'NCBP2_hg2', 'NKRF_hg2', 'NOLC1_hg2', 'NOLC1_k5', 'NONO_k5', 'NOP56_parclip', 'NOP58_parclip', 'NUDT21_parclip', 'ORF1_parclip', 'P53_NONO_parclip', 'PABPC4_k5', 'PABPN1_hg2', 'PAPD5_parclip', 'PCBP1_k5', 'PCBP2_hg2', 'PPIG_hg2', 'PRPF4_hg2', 'PRPF8_hg2', 'PRPF8_k5', 'PTBP1_hg2', 'PTBP1_k5', 'PUM1_k5', 'PUM2_k5', 'PUM2_parclip', 'PolyPhen', 'PrimateAI', 'QKI_hg2', 'QKI_k5', 'QKI_parclip', 'RBFOX2_hg2', 'RBFOX2_k5', 'RBM10_parclip', 'RBM15_hg2', 'RBM15_k5', 'RBM20_parclip', 'RBM22_hg2', 'RBM22_k5', 'RBPMS_parclip', 'RPS3_hg2', 'RPS3_k5', 'RTCB_parclip', 'SAFB2_k5', 'SF3A3_hg2', 'SF3B4_hg2', 'SF3B4_k5', 'SFPQ_hg2', 'SIFT', 'SLTM_hg2', 'SLTM_k5', 'SMNDC1_k5', 'SND1_hg2', 'SND1_k5', 'SRRM4_parclip', 'SRSF1_hg2', 'SRSF1_k5', 'SSB_parclip', 'STRAND', 'SUB1_hg2', 'SUGP2_hg2', 'SpliceAI_delta_score', 'SpliceAI_pred', 'TAF15_parclip', 'TARDBP_k5', 'TARDBP_parclip', 'TIA1_hg2', 'TIA1_k5', 'TIAL1_hg2', 'TRA2A_k5', 'U2AF1_hg2', 'U2AF1_k5', 'U2AF2_hg2', 'U2AF2_k5', 'UCHL5_hg2', 'UCHL5_k5', 'UPF1_hg2', 'UPF1_k5', 'UPF1_parclip', 'XPO5_hg2', 'XPO5_parclip', 'XRN2_hg2', 'XRN2_k5', 'YBX3_hg2', 'YBX3_k5', 'ZC3H11A_hg2', 'ZC3H11A_k5', 'ZC3H7B_parclip', 'ZFP36_parclip', 'ZNF622_k5', 'ZNF800_hg2', 'ZNF800_k5', 'alt', 'chrom', 'id', 'index', 'pos', 'ref']. {'Consequence_transcript_ablation'} are columns being either only in existing file or only in new data. This is not possible.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PATH/deeprvat/annotations/annotations.py", line 2119, in <module>
    cli()
  File "PATH/miniconda3/envs/deeprvat_annotations/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "PATH/miniconda3/envs/deeprvat_annotations/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "PATH/miniconda3/envs/deeprvat_annotations/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "PATH/miniconda3/envs/deeprvat_annotations/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "PATH/miniconda3/envs/deeprvat_annotations/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "PATH/deeprvat/annotations/annotations.py", line 1955, in concat_annotations
    raise ValueError
ValueError`

`Consequence_transcript_ablation` seems to be the problematic column. I cannot rule out with 100% certainty, that it is a mix up of old and new code / generated data on my side or that the cause is the deviation described in #61. Would greatly appreciate your insights!

**Comment by Marcel-Mueck** [comment]
Hello Jonas, thank you very much for your issue. I looked into it, and it seems like I missed a few possible output columns that VEP generates in the Consequence column inside the `process_vep` function.  `Consequence_transcript_ablation` was one of them, I will add this to the `process_vep` and push it to the main branch.
